name: Build and Push Docker Images to ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: cinecloudacr2026.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend Image (v2)
        run: |
          docker build -t cinecloudacr2026.azurecr.io/cinecloud-backend:v2 ./backend
          docker push cinecloudacr2026.azurecr.io/cinecloud-backend:v2

      - name: Build and Push Frontend Image (v1)
        run: |
          docker build -t cinecloudacr2026.azurecr.io/cinecloud-frontend:v1 ./frontend
          docker push cinecloudacr2026.azurecr.io/cinecloud-frontend:v1
